/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAnalyticsResponse {
  'averageSlotsPerSession' : bigint,
  'recentActivity' : Array<AnalyticsEvent>,
  'dayAwareClashFrequency' : Array<[string, bigint]>,
  'dailyUsage' : Array<[string, bigint]>,
  'slotPopularity' : Array<[string, bigint]>,
  'totalSessions' : bigint,
  'totalCourses' : bigint,
  'uniqueUsers' : bigint,
}
export interface AnalyticsEvent {
  'courseCount' : bigint,
  'duration' : bigint,
  'clashCount' : bigint,
  'slotCount' : bigint,
  'daySpecific' : boolean,
  'timestamp' : Time,
  'sessionId' : string,
  'affectedSlots' : Array<string>,
  'eventType' : AnalyticsEventType,
}
export type AnalyticsEventType = { 'clashDetected' : null } |
  { 'sessionStart' : null } |
  { 'courseRemoved' : null } |
  { 'courseCreated' : null } |
  { 'slotSelected' : null } |
  { 'reset' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Time = bigint;
export interface TimetableSlot {
  'id' : string,
  'day' : bigint,
  'timePeriod' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__analyticsEvents' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<AnalyticsEvent>
  >,
  '__clashFrequency' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, bigint]>
  >,
  '__dailyUsage' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, bigint]>
  >,
  '__sessionIds' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, null]>
  >,
  '__slotPopularity' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, bigint]>
  >,
  '__timetableSlots' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, TimetableSlot]>
  >,
  '__userProfiles' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserProfile]>
  >,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addTimetableSlot' : ActorMethod<[TimetableSlot], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminAnalytics' : ActorMethod<[string], AdminAnalyticsResponse>,
  'getAllTimetableSlots' : ActorMethod<[], Array<TimetableSlot>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDayLabel' : ActorMethod<[bigint], [] | [string]>,
  'getTimePeriodLabel' : ActorMethod<[bigint], [] | [string]>,
  'getTimetableSlot' : ActorMethod<[string], [] | [TimetableSlot]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'trackEvent' : ActorMethod<[AnalyticsEvent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];