/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AnalyticsEventType = IDL.Variant({
  'clashDetected' : IDL.Null,
  'sessionStart' : IDL.Null,
  'courseRemoved' : IDL.Null,
  'courseCreated' : IDL.Null,
  'slotSelected' : IDL.Null,
  'reset' : IDL.Null,
});
export const AnalyticsEvent = IDL.Record({
  'courseCount' : IDL.Nat,
  'duration' : IDL.Nat,
  'clashCount' : IDL.Nat,
  'slotCount' : IDL.Nat,
  'daySpecific' : IDL.Bool,
  'timestamp' : Time,
  'sessionId' : IDL.Text,
  'affectedSlots' : IDL.Vec(IDL.Text),
  'eventType' : AnalyticsEventType,
});
export const TimetableSlot = IDL.Record({
  'id' : IDL.Text,
  'day' : IDL.Nat,
  'timePeriod' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminAnalyticsResponse = IDL.Record({
  'averageSlotsPerSession' : IDL.Nat,
  'recentActivity' : IDL.Vec(AnalyticsEvent),
  'dayAwareClashFrequency' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'dailyUsage' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'slotPopularity' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalSessions' : IDL.Nat,
  'totalCourses' : IDL.Nat,
  'uniqueUsers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__analyticsEvents' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(AnalyticsEvent)],
      ['query'],
    ),
  '__clashFrequency' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  '__dailyUsage' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  '__sessionIds' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Null))],
      ['query'],
    ),
  '__slotPopularity' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  '__timetableSlots' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, TimetableSlot))],
      ['query'],
    ),
  '__userProfiles' : IDL.Func(
      [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addTimetableSlot' : IDL.Func([TimetableSlot], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminAnalytics' : IDL.Func(
      [IDL.Text],
      [AdminAnalyticsResponse],
      ['query'],
    ),
  'getAllTimetableSlots' : IDL.Func([], [IDL.Vec(TimetableSlot)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDayLabel' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getTimePeriodLabel' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getTimetableSlot' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TimetableSlot)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'trackEvent' : IDL.Func([AnalyticsEvent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AnalyticsEventType = IDL.Variant({
    'clashDetected' : IDL.Null,
    'sessionStart' : IDL.Null,
    'courseRemoved' : IDL.Null,
    'courseCreated' : IDL.Null,
    'slotSelected' : IDL.Null,
    'reset' : IDL.Null,
  });
  const AnalyticsEvent = IDL.Record({
    'courseCount' : IDL.Nat,
    'duration' : IDL.Nat,
    'clashCount' : IDL.Nat,
    'slotCount' : IDL.Nat,
    'daySpecific' : IDL.Bool,
    'timestamp' : Time,
    'sessionId' : IDL.Text,
    'affectedSlots' : IDL.Vec(IDL.Text),
    'eventType' : AnalyticsEventType,
  });
  const TimetableSlot = IDL.Record({
    'id' : IDL.Text,
    'day' : IDL.Nat,
    'timePeriod' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminAnalyticsResponse = IDL.Record({
    'averageSlotsPerSession' : IDL.Nat,
    'recentActivity' : IDL.Vec(AnalyticsEvent),
    'dayAwareClashFrequency' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'dailyUsage' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'slotPopularity' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalSessions' : IDL.Nat,
    'totalCourses' : IDL.Nat,
    'uniqueUsers' : IDL.Nat,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__analyticsEvents' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(AnalyticsEvent)],
        ['query'],
      ),
    '__clashFrequency' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    '__dailyUsage' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    '__sessionIds' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Null))],
        ['query'],
      ),
    '__slotPopularity' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    '__timetableSlots' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, TimetableSlot))],
        ['query'],
      ),
    '__userProfiles' : IDL.Func(
        [IDL.Opt(IDL.Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addTimetableSlot' : IDL.Func([TimetableSlot], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminAnalytics' : IDL.Func(
        [IDL.Text],
        [AdminAnalyticsResponse],
        ['query'],
      ),
    'getAllTimetableSlots' : IDL.Func([], [IDL.Vec(TimetableSlot)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDayLabel' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getTimePeriodLabel' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getTimetableSlot' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TimetableSlot)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'trackEvent' : IDL.Func([AnalyticsEvent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };