/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface TimetableSlot {
    id: string;
    day: bigint;
    timePeriod: bigint;
}
export type Time = bigint;
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface AnalyticsEvent {
    courseCount: bigint;
    duration: bigint;
    clashCount: bigint;
    slotCount: bigint;
    daySpecific: boolean;
    timestamp: Time;
    sessionId: string;
    affectedSlots: Array<string>;
    eventType: AnalyticsEventType;
}
export interface AdminAnalyticsResponse {
    averageSlotsPerSession: bigint;
    recentActivity: Array<AnalyticsEvent>;
    dayAwareClashFrequency: Array<[string, bigint]>;
    dailyUsage: Array<[string, bigint]>;
    slotPopularity: Array<[string, bigint]>;
    totalSessions: bigint;
    totalCourses: bigint;
    uniqueUsers: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface UserProfile {
    name: string;
}
export enum AnalyticsEventType {
    clashDetected = "clashDetected",
    sessionStart = "sessionStart",
    courseRemoved = "courseRemoved",
    courseCreated = "courseCreated",
    slotSelected = "slotSelected",
    reset = "reset"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __analyticsEvents(io: bigint | null, count: bigint | null): Promise<Array<AnalyticsEvent>>;
    __clashFrequency(ko: string | null, count: bigint | null): Promise<Array<[string, bigint]>>;
    __dailyUsage(ko: string | null, count: bigint | null): Promise<Array<[string, bigint]>>;
    __sessionIds(ko: string | null, count: bigint | null): Promise<Array<[string, null]>>;
    __slotPopularity(ko: string | null, count: bigint | null): Promise<Array<[string, bigint]>>;
    __timetableSlots(ko: string | null, count: bigint | null): Promise<Array<[string, TimetableSlot]>>;
    __userProfiles(ko: Principal | null, count: bigint | null): Promise<Array<[Principal, UserProfile]>>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addTimetableSlot(slot: TimetableSlot): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAdminAnalytics(adminKey: string): Promise<AdminAnalyticsResponse>;
    getAllTimetableSlots(): Promise<Array<TimetableSlot>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDayLabel(day: bigint): Promise<string | null>;
    getTimePeriodLabel(timePeriod: bigint): Promise<string | null>;
    getTimetableSlot(slotId: string): Promise<TimetableSlot | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    trackEvent(event: AnalyticsEvent): Promise<void>;
}
import type { AdminAnalyticsResponse as _AdminAnalyticsResponse, AnalyticsEvent as _AnalyticsEvent, AnalyticsEventType as _AnalyticsEventType, Error as _Error, Result as _Result, Time as _Time, TimetableSlot as _TimetableSlot, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __analyticsEvents(arg0: bigint | null, arg1: bigint | null): Promise<Array<AnalyticsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.__analyticsEvents(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__analyticsEvents(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __clashFrequency(arg0: string | null, arg1: bigint | null): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__clashFrequency(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__clashFrequency(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __dailyUsage(arg0: string | null, arg1: bigint | null): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__dailyUsage(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__dailyUsage(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __sessionIds(arg0: string | null, arg1: bigint | null): Promise<Array<[string, null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__sessionIds(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__sessionIds(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __slotPopularity(arg0: string | null, arg1: bigint | null): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__slotPopularity(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__slotPopularity(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __timetableSlots(arg0: string | null, arg1: bigint | null): Promise<Array<[string, TimetableSlot]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__timetableSlots(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__timetableSlots(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __userProfiles(arg0: Principal | null, arg1: bigint | null): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__userProfiles(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__userProfiles(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addTimetableSlot(arg0: TimetableSlot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTimetableSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTimetableSlot(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAdminAnalytics(arg0: string): Promise<AdminAnalyticsResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAnalytics(arg0);
                return from_candid_AdminAnalyticsResponse_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAnalytics(arg0);
            return from_candid_AdminAnalyticsResponse_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTimetableSlots(): Promise<Array<TimetableSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimetableSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimetableSlots();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDayLabel(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDayLabel(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDayLabel(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimePeriodLabel(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimePeriodLabel(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimePeriodLabel(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimetableSlot(arg0: string): Promise<TimetableSlot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimetableSlot(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimetableSlot(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async trackEvent(arg0: AnalyticsEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackEvent(to_candid_AnalyticsEvent_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackEvent(to_candid_AnalyticsEvent_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AdminAnalyticsResponse_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminAnalyticsResponse): AdminAnalyticsResponse {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_AnalyticsEventType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsEventType): AnalyticsEventType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_AnalyticsEvent_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsEvent): AnalyticsEvent {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimetableSlot]): TimetableSlot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageSlotsPerSession: bigint;
    recentActivity: Array<_AnalyticsEvent>;
    dayAwareClashFrequency: Array<[string, bigint]>;
    dailyUsage: Array<[string, bigint]>;
    slotPopularity: Array<[string, bigint]>;
    totalSessions: bigint;
    totalCourses: bigint;
    uniqueUsers: bigint;
}): {
    averageSlotsPerSession: bigint;
    recentActivity: Array<AnalyticsEvent>;
    dayAwareClashFrequency: Array<[string, bigint]>;
    dailyUsage: Array<[string, bigint]>;
    slotPopularity: Array<[string, bigint]>;
    totalSessions: bigint;
    totalCourses: bigint;
    uniqueUsers: bigint;
} {
    return {
        averageSlotsPerSession: value.averageSlotsPerSession,
        recentActivity: from_candid_vec_n2(_uploadFile, _downloadFile, value.recentActivity),
        dayAwareClashFrequency: value.dayAwareClashFrequency,
        dailyUsage: value.dailyUsage,
        slotPopularity: value.slotPopularity,
        totalSessions: value.totalSessions,
        totalCourses: value.totalCourses,
        uniqueUsers: value.uniqueUsers
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    courseCount: bigint;
    duration: bigint;
    clashCount: bigint;
    slotCount: bigint;
    daySpecific: boolean;
    timestamp: _Time;
    sessionId: string;
    affectedSlots: Array<string>;
    eventType: _AnalyticsEventType;
}): {
    courseCount: bigint;
    duration: bigint;
    clashCount: bigint;
    slotCount: bigint;
    daySpecific: boolean;
    timestamp: Time;
    sessionId: string;
    affectedSlots: Array<string>;
    eventType: AnalyticsEventType;
} {
    return {
        courseCount: value.courseCount,
        duration: value.duration,
        clashCount: value.clashCount,
        slotCount: value.slotCount,
        daySpecific: value.daySpecific,
        timestamp: value.timestamp,
        sessionId: value.sessionId,
        affectedSlots: value.affectedSlots,
        eventType: from_candid_AnalyticsEventType_n5(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n11(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clashDetected: null;
} | {
    sessionStart: null;
} | {
    courseRemoved: null;
} | {
    courseCreated: null;
} | {
    slotSelected: null;
} | {
    reset: null;
}): AnalyticsEventType {
    return "clashDetected" in value ? AnalyticsEventType.clashDetected : "sessionStart" in value ? AnalyticsEventType.sessionStart : "courseRemoved" in value ? AnalyticsEventType.courseRemoved : "courseCreated" in value ? AnalyticsEventType.courseCreated : "slotSelected" in value ? AnalyticsEventType.slotSelected : "reset" in value ? AnalyticsEventType.reset : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalyticsEvent>): Array<AnalyticsEvent> {
    return value.map((x)=>from_candid_AnalyticsEvent_n3(_uploadFile, _downloadFile, x));
}
function to_candid_AnalyticsEventType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalyticsEventType): _AnalyticsEventType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_AnalyticsEvent_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalyticsEvent): _AnalyticsEvent {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    courseCount: bigint;
    duration: bigint;
    clashCount: bigint;
    slotCount: bigint;
    daySpecific: boolean;
    timestamp: Time;
    sessionId: string;
    affectedSlots: Array<string>;
    eventType: AnalyticsEventType;
}): {
    courseCount: bigint;
    duration: bigint;
    clashCount: bigint;
    slotCount: bigint;
    daySpecific: boolean;
    timestamp: _Time;
    sessionId: string;
    affectedSlots: Array<string>;
    eventType: _AnalyticsEventType;
} {
    return {
        courseCount: value.courseCount,
        duration: value.duration,
        clashCount: value.clashCount,
        slotCount: value.slotCount,
        daySpecific: value.daySpecific,
        timestamp: value.timestamp,
        sessionId: value.sessionId,
        affectedSlots: value.affectedSlots,
        eventType: to_candid_AnalyticsEventType_n24(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalyticsEventType): {
    clashDetected: null;
} | {
    sessionStart: null;
} | {
    courseRemoved: null;
} | {
    courseCreated: null;
} | {
    slotSelected: null;
} | {
    reset: null;
} {
    return value == AnalyticsEventType.clashDetected ? {
        clashDetected: null
    } : value == AnalyticsEventType.sessionStart ? {
        sessionStart: null
    } : value == AnalyticsEventType.courseRemoved ? {
        courseRemoved: null
    } : value == AnalyticsEventType.courseCreated ? {
        courseCreated: null
    } : value == AnalyticsEventType.slotSelected ? {
        slotSelected: null
    } : value == AnalyticsEventType.reset ? {
        reset: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
